package com.films4you.req1;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class RequirementTest {
  
  /**
   * A sample test. You'll need to test your solution properly.
   */
	
  @Test
  public void testRequirementGetActual() {
    Requirement r = new Requirement();
    assertEquals("DADDY PITTSBURGH\n"
    		+ "DAISY MENAGERIE\n"
    		+ "DALMATIONS SWEDEN\n"
    		+ "DANCES NONE\n"
    		+ "DANCING FEVER\n"
    		+ "DANGEROUS UPTOWN\n"
    		+ "DARES PLUTO\n"
    		+ "DARKNESS WAR\n"
    		+ "DARKO DORADO\n"
    		+ "DARLING BREAKING\n"
    		+ "DARN FORRESTER\n"
    		+ "DATE SPEED\n"
    		+ "DAUGHTER MADIGAN\n"
    		+ "DAWN POND\n"
    		+ "DAY UNFAITHFUL\n"
    		+ "DAZED PUNK\n"
    		+ "DECEIVER BETRAYED\n"
    		+ "DEEP CRUSADE\n"
    		+ "DEER VIRGINIAN\n"
    		+ "DELIVERANCE MULHOLLAND\n"
    		+ "DESERT POSEIDON\n"
    		+ "DESIRE ALIEN\n"
    		+ "DESPERATE TRAINSPOTTING\n"
    		+ "DESTINATION JERK\n"
    		+ "DESTINY SATURDAY\n"
    		+ "DETAILS PACKER\n"
    		+ "DETECTIVE VISION\n"
    		+ "DEVIL DESIRE\n"
    		+ "DIARY PANIC\n"
    		+ "DINOSAUR SECRETARY\n"
    		+ "DIRTY ACE\n"
    		+ "DISCIPLE MOTHER\n"
    		+ "DISTURBING SCARFACE\n"
    		+ "DIVIDE MONSTER\n"
    		+ "DIVINE RESURRECTION\n"
    		+ "DIVORCE SHINING\n"
    		+ "DOCTOR GRAIL\n"
    		+ "DOGMA FAMILY\n"
    		+ "DOLLS RAGE\n"
    		+ "DONNIE ALLEY\n"
    		+ "DOOM DANCING\n"
    		+ "DOORS PRESIDENT\n"
    		+ "DORADO NOTTING\n"
    		+ "DOUBLE WRATH\n"
    		+ "DOUBTFIRE LABYRINTH\n"
    		+ "DOWNHILL ENOUGH\n"
    		+ "DOZEN LION\n"
    		+ "DRACULA CRYSTAL\n"
    		+ "DRAGON SQUAD\n"
    		+ "DRAGONFLY STRANGERS\n"
    		+ "DREAM PICKUP\n"
    		+ "DRIFTER COMMANDMENTS\n"
    		+ "DRIVER ANNIE\n"
    		+ "DRIVING POLISH\n"
    		+ "DROP WATERFRONT\n"
    		+ "DRUMLINE CYCLONE\n"
    		+ "DRUMS DYNAMITE\n"
    		+ "DUCK RACER\n"
    		+ "DUDE BLINDNESS\n"
    		+ "DUFFEL APOCALYPSE\n"
    		+ "DUMBO LUST\n"
    		+ "DURHAM PANKY\n"
    		+ "DWARFS ALTER\n"
    		+ "DYING MAKER\n"
    		+ "DYNAMITE TARZAN\n", r.getValueAsString());
  }
  
  
  @Test 
  public void testRequirementGetHumanReadable() {
	  Requirement r = new Requirement();
	  assertEquals("Film ID          Film Name\n"
	  		+ "202              DADDY PITTSBURGH\n"
	  		+ "203              DAISY MENAGERIE\n"
	  		+ "204              DALMATIONS SWEDEN\n"
	  		+ "205              DANCES NONE\n"
	  		+ "206              DANCING FEVER\n"
	  		+ "207              DANGEROUS UPTOWN\n"
	  		+ "208              DARES PLUTO\n"
	  		+ "209              DARKNESS WAR\n"
	  		+ "210              DARKO DORADO\n"
	  		+ "211              DARLING BREAKING\n"
	  		+ "212              DARN FORRESTER\n"
	  		+ "213              DATE SPEED\n"
	  		+ "214              DAUGHTER MADIGAN\n"
	  		+ "215              DAWN POND\n"
	  		+ "216              DAY UNFAITHFUL\n"
	  		+ "217              DAZED PUNK\n"
	  		+ "218              DECEIVER BETRAYED\n"
	  		+ "219              DEEP CRUSADE\n"
	  		+ "220              DEER VIRGINIAN\n"
	  		+ "221              DELIVERANCE MULHOLLAND\n"
	  		+ "222              DESERT POSEIDON\n"
	  		+ "223              DESIRE ALIEN\n"
	  		+ "224              DESPERATE TRAINSPOTTING\n"
	  		+ "225              DESTINATION JERK\n"
	  		+ "226              DESTINY SATURDAY\n"
	  		+ "227              DETAILS PACKER\n"
	  		+ "228              DETECTIVE VISION\n"
	  		+ "229              DEVIL DESIRE\n"
	  		+ "230              DIARY PANIC\n"
	  		+ "231              DINOSAUR SECRETARY\n"
	  		+ "232              DIRTY ACE\n"
	  		+ "233              DISCIPLE MOTHER\n"
	  		+ "234              DISTURBING SCARFACE\n"
	  		+ "235              DIVIDE MONSTER\n"
	  		+ "236              DIVINE RESURRECTION\n"
	  		+ "237              DIVORCE SHINING\n"
	  		+ "238              DOCTOR GRAIL\n"
	  		+ "239              DOGMA FAMILY\n"
	  		+ "240              DOLLS RAGE\n"
	  		+ "241              DONNIE ALLEY\n"
	  		+ "242              DOOM DANCING\n"
	  		+ "243              DOORS PRESIDENT\n"
	  		+ "244              DORADO NOTTING\n"
	  		+ "245              DOUBLE WRATH\n"
	  		+ "246              DOUBTFIRE LABYRINTH\n"
	  		+ "247              DOWNHILL ENOUGH\n"
	  		+ "248              DOZEN LION\n"
	  		+ "249              DRACULA CRYSTAL\n"
	  		+ "250              DRAGON SQUAD\n"
	  		+ "251              DRAGONFLY STRANGERS\n"
	  		+ "252              DREAM PICKUP\n"
	  		+ "253              DRIFTER COMMANDMENTS\n"
	  		+ "254              DRIVER ANNIE\n"
	  		+ "255              DRIVING POLISH\n"
	  		+ "256              DROP WATERFRONT\n"
	  		+ "257              DRUMLINE CYCLONE\n"
	  		+ "258              DRUMS DYNAMITE\n"
	  		+ "259              DUCK RACER\n"
	  		+ "260              DUDE BLINDNESS\n"
	  		+ "261              DUFFEL APOCALYPSE\n"
	  		+ "262              DUMBO LUST\n"
	  		+ "263              DURHAM PANKY\n"
	  		+ "264              DWARFS ALTER\n"
	  		+ "265              DYING MAKER\n"
	  		+ "266              DYNAMITE TARZAN\n", r.getHumanReadable());
  }
}
